version: '3'
services:
  fluentd:
    build:
      context: ./dockerfiles/fluentd/
    volumes:
      - "./dockerfiles/fluentd/conf:/fluentd/etc"
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"

  kibana:
    image: kibana:7.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
